stages:
  prepare:
    cmd: PYTHONPATH=. python src/data/make_dataset.py
    deps:
      - data/raw/obesity_estimation_modified.csv
      - src/data/make_dataset.py
    outs:
      - data/processed/obesity_estimation_clean.csv

  eda:
    cmd: PYTHONPATH=. python src/visualization/eda.py
    deps:
      - data/processed/obesity_estimation_clean.csv
      - src/visualization/eda.py
    outs:
      - reports/figures

  preprocessing:
    cmd: PYTHONPATH=. python src/data/preprocess_dataset.py
    deps:
      - data/processed/obesity_estimation_clean.csv
      - src/data/preprocess_dataset.py
    outs:
      - data/interim/train_prepared.csv
      - data/interim/test_prepared.csv
      - data/interim/preprocessor.pkl
      - data/interim/class_distribution.csv

  training:
    cmd: PYTHONPATH=. python src/models/train_model.py
    deps:
      - data/interim/train_prepared.csv
      - src/models/train_model.py
      - src/models/utils.py
    outs:
      - models/

  evaluation:
    cmd: PYTHONPATH=. python src/models/evaluate_model.py
    deps:
      - data/interim/test_prepared.csv
      - models/
      - src/models/evaluate_model.py
      - src/models/utils.py
    outs:
      - reports/confusion_matrix.csv
      - reports/confusion_matrix.png
    metrics:
      - reports/evaluation_results.csv
