stages:
  prepare:
    cmd: python src/data/make_dataset.py
    deps:
      - data/raw/obesity_estimation_modified.csv
      - src/data/make_dataset.py
    outs:
      - data/processed/obesity_estimation_clean.csv

  eda:
    cmd: python src/visualization/eda_manual.py
    deps:
      - data/processed/obesity_estimation_clean.csv
      - src/visualization/eda_manual.py
    outs:
      - reports/figures

  preprocessing:
    cmd: python src/data/preprocess_dataset.py
    deps:
      - data/processed/obesity_estimation_clean.csv
      - src/data/preprocess_dataset.py
    outs:
      - data/interim/train_prepared.csv
      - data/interim/test_prepared.csv
      - data/interim/preprocessor.pkl

  training:
    cmd: python src/models/train_model.py
    deps:
      - data/interim/train_prepared.csv
      - data/interim/test_prepared.csv
      - src/models/train_model.py
    outs:
      - models/best_model.pkl
      - reports/confusion_matrix.csv
      - reports/confusion_matrix.png
    metrics:
      - reports/model_comparison.csv
      - reports/final_model_comparison.csv
