---
stages:
  prepare:
    cmd: PYTHONPATH=. python obesity_estimator/dataset.py
    deps:
      - data/raw/obesity_estimation_modified.csv
      - obesity_estimator/dataset.py
    outs:
      - data/processed/obesity_estimation_clean.csv

  eda:
    cmd: PYTHONPATH=. python obesity_estimator/plots.py
    deps:
      - data/processed/obesity_estimation_clean.csv
      - obesity_estimator/plots.py
    outs:
      - reports/figures/eda

  preprocessing:
    cmd: PYTHONPATH=. python obesity_estimator/features.py
    deps:
      - data/processed/obesity_estimation_clean.csv
      - obesity_estimator/features.py
    outs:
      - data/interim/train_prepared.csv
      - data/interim/test_prepared.csv
      - data/interim/preprocessor.pkl
      - data/interim/class_distribution.csv

  training:
    cmd: PYTHONPATH=. python obesity_estimator/modeling/train.py
    deps:
      - obesity_estimator/modeling/train.py
      - data/interim/train_prepared.csv
      - data/interim/test_prepared.csv
    outs:
      - models/best_model.joblib
    metrics:
      - reports/metrics.json
    plots:
      - reports/figures/confusion_matrix.png

  evaluation:
    cmd: PYTHONPATH=. python obesity_estimator/modeling/predict.py
    deps:
      - data/interim/test_prepared.csv
      - models/
      - obesity_estimator/modeling/predict.py
      - obesity_estimator/utils.py
    outs:
      - reports/confusion_matrix.csv
      - reports/confusion_matrix.png
    metrics:
      - reports/evaluation_results.csv

  model_plots:
    cmd: PYTHONPATH=. python obesity_estimator/modeling/plot_curves.py
    deps:
      - obesity_estimator/modeling/plot_curves.py
      - data/interim/test_prepared.csv
      - models/best_model.joblib
      - models/logistic_regression_best.joblib
      - models/random_forest_best.joblib
      - models/hist_gradient_boosting_best.joblib
      - models/svc_rbf_best.joblib
    outs:
      - reports/figures/models
      - reports/roc_auc_by_model.csv
      - reports/pr_auc_by_model.csv

