stages:
  prepare:
    cmd: PYTHONPATH=. python obesity_estimator/dataset.py
    deps:
      - data/raw/obesity_estimation_modified.csv
      - obesity_estimator/dataset.py
    outs:
      - data/processed/obesity_estimation_clean.csv

  eda:
    cmd: PYTHONPATH=. python obesity_estimator/plots.py
    deps:
      - data/processed/obesity_estimation_clean.csv
      - obesity_estimator/plots.py
    outs:
      - reports/figures/eda

  preprocessing:
    cmd: PYTHONPATH=. python obesity_estimator/features.py
    deps:
      - data/processed/obesity_estimation_clean.csv
      - obesity_estimator/features.py
    outs:
      - data/interim/train_prepared.csv
      - data/interim/test_prepared.csv
      - data/interim/preprocessor.pkl
      - data/interim/class_distribution.csv

  training:
    # Entrenamiento con Grid/Random search y comparación de modelos (versión mejorada)
    cmd: PYTHONPATH=. python obesity_estimator/modeling/train.py
    deps:
      - obesity_estimator/modeling/train.py
      - obesity_estimator/config.py
      - obesity_estimator/utils.py
      - data/prepared/train_prepared.csv
      - data/prepared/test_prepared.csv
      - data/prepared/y_train.csv
      - data/prepared/y_test.csv
    outs:
      - models/best_model.joblib
    metrics:
      - reports/metrics.json
    plots:
      # El training guarda su figura en SU PROPIA subcarpeta
      - reports/figures/training/confusion_matrix.png

  evaluation:
    cmd: PYTHONPATH=. python obesity_estimator/modeling/predict.py
    deps:
      - data/interim/test_prepared.csv
      - models/
      - obesity_estimator/modeling/predict.py
      - obesity_estimator/utils.py
    outs:
      - reports/confusion_matrix.csv
      - reports/confusion_matrix.png
    metrics:
      - reports/evaluation_results.csv
